spring.application.name=chapter2-restful-api

# Thông tin kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/company_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Yêu cầu Hibernate tự động tạo bảng (table) dựa trên code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true