spring.application.name=order-service
server.port=8082
# Kết nối đến PostgreSQL (Thay 'mydb', 'postgres', 'password' bằng thông tin thực tế của bạn)
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate tự động cập nhật cấu trúc bảng
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trong console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect